# Generated by Django 5.2.6 on 2025-09-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='fecha_de_visita',
            new_name='hora_de_entrada_y_salida',
        ),
    ]
