# Generated by Django 5.2.6 on 2025-09-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitas', '0002_rename_fecha_de_visita_visita_hora_de_entrada_y_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fecha_de_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
