# Generated by Django 5.2.6 on 2025-09-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visitas', '0003_visita_fecha_de_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='fecha_de_salida',
        ),
    ]
